### ISSUE TITLE
Support meta data with arrays

### ISSUE THREAD

**Issue by zanerock** [liquid-labs/federated-json#12]
## Objectives

While supported, arrays are a bit different from objects in that you can't attach meta data to them (at least in the JSON world). So, rather than have just naked local top-level array, we could also support 'wrapped arrays' where the meta data tells us that the item is actually an array and we're wrapping it just so we have someplace to put the metadata.

## Deliverables

* [ ] Support meta data field "discardOuterObject", if 'true' then the outer object is discarded and the inner content object is returned.
* [ ] If there is no `content` field on the object, throw an error.
* [ ] If the outer object has any fields other that `_meta` and `content`, throw an error.
* [ ] Attach `_meta` as a non-iterated field to the resulting array. (I believe this will work, follow up if not.)
